server:
  port: 9002
  servlet:
    context-path: /demo
  tomcat:
    max-connections: 1000
    accept-count: 1000
    threads:
      max: 1000
spring:
  datasource:
    task:
      url: jdbc:mysql://localhost:3306/click?characterEncoding=utf-8
      username: root
      password: Pass1234